### ISSUE TITLE
Trocar ícone e alinhar

### ISSUE THREAD

**Issue by gamito** [puredreamer/gulp-project#6]
Este ícone (em desktop) deveria ser trocado já que colapsar o menu, normalmente, não é representado pelo hamburguer.

Alinhar o title.

![image](https://user-images.githubusercontent.com/334137/77932492-85e88580-72a5-11ea-9a5a-f2fbbe7affd7.png)

**Comment by puredreamer** [comment]
resolvido. falta só tratar da animação do hamburguer

**Comment by puredreamer** [comment]
feito
